#
# This docker compose is useful only for the local development and debugging.
# No of this assertion is related to the deployment in development / staging / production environment
#
version: '3'
services:
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPassword123

  web-api:
    build:
      context: .
      args:
        Environment: Docker
    ports:
      - "80:80"
    links:
      - "database"
    depends_on: 
      - "database"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Docker
    command: sh -c "sleep 20s && dotnet Azure.Web.Api.dll"
